# Generated by Django 4.1.4 on 2022-12-28 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="Fact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("slug", models.SlugField()),
                ("source", models.URLField(blank=True, null=True)),
                ("tags", models.ManyToManyField(to="questions.tag")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
