# Generated by Django 4.1.4 on 2022-12-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0002_question_is_active_fact"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="explanation",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="explanation_de",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="explanation_en",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
