# Generated by Django 4.1.4 on 2022-12-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0004_alter_answer_text_alter_answer_text_de_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fact",
            name="slug",
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name="question",
            name="slug",
            field=models.SlugField(max_length=255),
        ),
    ]
